### PR TITLE
Support download assets

### PR DESCRIPTION
**Pull request by ggrossetie**

### CODE REVIEW

**Comment by ggrossetie** [comment]
@mraible with this pull request you will be able to display a list of assets (download links).

Here, I'm using 3 assets:
```
:page-downloadable-asset-keys: pdf-web,pdf-print,epub
```

For each asset, we can define a URL and a title:
```
:page-downloadable-asset-pdf-web-title: PDF (web)
:page-downloadable-asset-pdf-web-link: attachment$pdf-web/index.pdf
:page-downloadable-asset-pdf-print-title: PDF (print)
:page-downloadable-asset-pdf-print-link: attachment$pdf-print/index.pdf
:page-downloadable-asset-epub-title: EPUB3
:page-downloadable-asset-epub-link: attachment$epub3/index.epub
```

And here's the result:
Capture d’écran 2023-01-19 à 15 25 00

The icon is inferred from the asset key.

**Comment by mraible** [comment]
Thanks, @Mogztter! I'm not sure PDF (print) is necessary since printing it on a printer is different from printing a hard copy of the book. 

Also, I believe this will work for a project that releases its assets on GitHub. However, for something like InfoQ, the [landing page](https://www.infoq.com/minibooks/jhipster-mini-book-5/) prompts you to log in when you click on the buttons. 

When you are logged in, it does show the buttons, but they're not links. They call JavaScript functions that show you a sponsor's ad first. 

Screenshot 2023-01-20 at 10 22 14

Because of this, it might be good to have a 2nd option. Instead of "Download as", maybe "Download from" would be better and you can set the title and link to a landing page.

**Comment by ggrossetie** [comment]
That's a good point.

> Because of this, it might be good to have a 2nd option. Instead of "Download as", maybe "Download from" would be better and you can set the title and link to a landing page.

We could introduce an option to control the title, `page-downloadable-asset-title`? with a default value of "Download as".

> However, for something like InfoQ, the [landing page](https://www.infoq.com/minibooks/jhipster-mini-book-5/) prompts you to log in when you click on the buttons.

For the JHipster mini book, the link should be https://www.infoq.com/minibooks/jhipster-mini-book-5/ and the title "Download from" right? Should we have a single link? "Download from InfoQ"? Any preference regarding the icon?

**Comment by mraible** [comment]
> We could introduce an option to control the title, `page-downloadable-asset-title?` with a default value of "Download as".

Sounds good to me!

For the JHipster Mini-Book, your assumptions are correct. I think "Download from InfoQ" would be good. Is there a "download" icon that can be used? If not, maybe just use a book icon?

I think some folks might want to use this feature to link to a landing page for downloads. For example, you could say "Download from GitHub" and link to a release.

**Comment by ggrossetie** [comment]
We are using https://feathericons.com/ so we could use: download

> I think some folks might want to use this feature to link to a landing page for downloads. For example, you could say "Download from GitHub" and link to a release.

👍🏻

**Comment by ggrossetie** [comment]
Capture d’écran 2023-01-20 à 18 27 43

```
:page-downloadable-asset-title: Download from
:page-downloadable-asset-keys: infoq
:page-downloadable-asset-infoq-title: InfoQ
:page-downloadable-asset-infoq-link: https://infoq.com/minibooks/jhipster-mini-book-5
:page-downloadable-asset-infoq-icon: download
```

**Comment by mraible** [comment]
Excellent! 

Part of me thinks it'd be better to have:

```
[ icon ] Download from InfoQ
```

But I think that might be hard to support, especially with the individual icons too.

**Comment by ggrossetie** [comment]
Another idea would be to use an InfoQ icon without a text:

Capture d’écran 2023-01-20 à 18 49 20

**Comment by mraible** [comment]
It looks really good with the icon! Maybe even make the text color changeable so you can match the icon's color.

**Comment by ggrossetie** [comment]
> It looks really good with the icon! Maybe even make the text color changeable so you can match the icon's color.

You want to update the "Download from" text color?

**Comment by mraible** [comment]
Yes, but only if it's easy to implement.On Jan 22, 2023, at 04:06, Guillaume Grossetie ***@***.***> wrote:﻿

It looks really good with the icon! Maybe even make the text color changeable so you can match the icon's color.

You want to update the "Download from" text color?

**Comment by mraible** [comment]
On second thought, I think this is "good enough" and I can probably figure out how to modify the text with CSS. 

🚢

**Review by mraible — APPROVED** [review]

**Comment by ggrossetie** [comment]
Sorry about the delay.
I agree, using an attribute/setting is probably a bit too much since we can customize the UI using CSS.

**Pull request merged**
